version: '3.8'

volumes:
  jenkins_home:

services:
  jenkins:
    container_name: jenkins-lab01
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - JENKINS_ADMIN_ID=jenkins
      - JENKINS_ADMIN_PASSWORD=jenkins
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc.yaml:/var/jenkins_home/casc.yaml